# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: task/add.proto, task/animate.proto, task/delete.proto, task/norm_map.proto, task/rmbg.proto, task/stand.proto, task/status.proto, task/task.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Add",
    "AddCompleted",
    "Animate",
    "AnimateCompleted",
    "Cancelled",
    "Delete",
    "DeleteCompleted",
    "Failed",
    "NormMap",
    "NormMapCompleted",
    "Rmbg",
    "RmbgCompleted",
    "Stand",
    "StandCompleted",
    "Task",
    "TaskStatus",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class Add(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    character_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    asset_path: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    prompt: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    negative_prompt: "str | None" = betterproto2.field(
        5, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message("task", "Add", Add)


@dataclass(eq=False, repr=False)
class AddCompleted(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    character_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "AddCompleted", AddCompleted)


@dataclass(eq=False, repr=False)
class Animate(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    first_frame_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    last_frame_path: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    prompt: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    num_frames: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    loop: "bool | None" = betterproto2.field(6, betterproto2.TYPE_BOOL, optional=True)


default_message_pool.register_message("task", "Animate", Animate)


@dataclass(eq=False, repr=False)
class AnimateCompleted(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    frames_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "AnimateCompleted", AnimateCompleted)


@dataclass(eq=False, repr=False)
class Cancelled(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "Cancelled", Cancelled)


@dataclass(eq=False, repr=False)
class Delete(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    character_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    prompt: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    negative_prompt: "str | None" = betterproto2.field(
        4, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message("task", "Delete", Delete)


@dataclass(eq=False, repr=False)
class DeleteCompleted(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    character_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "DeleteCompleted", DeleteCompleted)


@dataclass(eq=False, repr=False)
class Failed(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    error_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    error_message: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "Failed", Failed)


@dataclass(eq=False, repr=False)
class NormMap(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    frames_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "NormMap", NormMap)


@dataclass(eq=False, repr=False)
class NormMapCompleted(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    frames_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "NormMapCompleted", NormMapCompleted)


@dataclass(eq=False, repr=False)
class Rmbg(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    frames_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "Rmbg", Rmbg)


@dataclass(eq=False, repr=False)
class RmbgCompleted(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    frames_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "RmbgCompleted", RmbgCompleted)


@dataclass(eq=False, repr=False)
class Stand(betterproto2.Message):
    id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    character_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    pose_path: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    prompt: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    negative_prompt: "str | None" = betterproto2.field(
        5, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message("task", "Stand", Stand)


@dataclass(eq=False, repr=False)
class StandCompleted(betterproto2.Message):
    task_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    character_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("task", "StandCompleted", StandCompleted)


@dataclass(eq=False, repr=False)
class Task(betterproto2.Message):
    """


    Oneofs:
        - task:
    """

    add: "Add | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="task"
    )

    delete: "Delete | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="task"
    )

    stand: "Stand | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="task"
    )

    animate: "Animate | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="task"
    )

    rmbg: "Rmbg | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="task"
    )

    norm_map: "NormMap | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="task"
    )


default_message_pool.register_message("task", "Task", Task)


@dataclass(eq=False, repr=False)
class TaskStatus(betterproto2.Message):
    """


    Oneofs:
        - status:
    """

    failed: "Failed | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )

    add_completed: "AddCompleted | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )

    delete_completed: "DeleteCompleted | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )

    stand_completed: "StandCompleted | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )

    animate_completed: "AnimateCompleted | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )

    rmbg_completed: "RmbgCompleted | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )

    norm_map_completed: "NormMapCompleted | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="status"
    )


default_message_pool.register_message("task", "TaskStatus", TaskStatus)
